version: "3.6"
services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b 0.0.0.0:5000 run:app
    volumes:
    - ./services/web/:/usr/src/app/
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=entrega0
    ports:
      - '5432:5432'

