version: "3.6"
services:
  flask_app:
    links:
      - 'postgres'
    depends_on:
      - postgres
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "5000:5000"
    command:  bash -c "gunicorn -w 1 -b 0.0.0.0:5000 run:app"
    # command: flask db init
    # command:  bash -c "flask db upgrade && gunicorn -w 1 -b 0.0.0.0:5000 run:app"
    # command: gunicorn -w 1 -b 0.0.0.0:5000 run:app
    # entrypoint: /flask_app/entrypoint.sh
    # command: ls app

    volumes:
    - ./app/:/usr/src/app/
    - ./migrations:/usr/src/app/migrations

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=entrega0
    ports:
      - '5432:5432'
    expose:
      - 5432

